language: node_js           # 声明构建语言环境
node_js:                    # node.js最低版本
  - "stable"

install:
  - npm install
  
script:
  - npm run build


deploy:                     # 部署
  provider: releases
  api_key: "GITHUB OAUTH TOKEN"
  file: "FILE TO UPLOAD"
  skip_cleanup: true
  #on:
  #  tags: true
